Put back required dependency on commons-logging:
  java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
      at org.hibernate.tool.hbm2x.AbstractExporter.<init>(AbstractExporter.java:25)
      at org.hibernate.tool.hbm2x.HibernateConfigurationExporter.<init>(HibernateConfigurationExporter.java:37)
      at org.hibernate.tool.ant.Hbm2CfgXmlExporterTask.createExporter(Hbm2CfgXmlExporterTask.java:19)
      at org.hibernate.tool.ant.ExporterTask.execute(ExporterTask.java:39)
      at org.hibernate.tool.ant.HibernateToolTask.execute(HibernateToolTask.java:186)